### ISSUE TITLE
ReferenceError: kommunicate is not defined

### ISSUE THREAD

**Issue by kinZz23** [Kommunicate-io/Kommunicate-Cordova-Ionic-PhoneGap-Chat-Plugin#1]
I am trying to use kommunicate for  my ionic project but it is giving me error "ReferenceError: kommunicate is not defined"

initial step: plugin installed via command "ionic cordova plugin add https://github.com/Kommunicate-io/Kommunicate-Cordova-Ionic-PhoneGap-Chat-Plugin.git"

made changes in code where on click on start conversation in event-names page the conversation should begin

**my event-names.html:**
<ion-footer no-shadow>
	<ion-toolbar position="bottom">
		<button ion-button full round (click)="showChatPage()">
    		<ion-icon name="chatbubbles"> Chat with Us!</ion-icon>
    	</button>
	</ion-toolbar>
</ion-footer>

**my event-names.ts code** 
showChatPage(){
    kommunicate.launchConversation((response)=>{
      var vary = {
        'agentId':'abc@som.edu',
        'botId': 'livefiesta-Assistant'
      };
      kommunicate.startNewConversation(vary, (response) => {
        var grpy = {
          'groupId' : response,
          'takeOrder' : true
        };
  
        console.log("Reytum Launch object : " + JSON.stringify(grpy));
  
        kommunicate.launchParticularConversation(grpy, function(response) {
          console.log("Kommunicate launch success response : " + response);
        }, function(response) {
          console.log("Kommunicate launch failure response : " + response);
        });
        
        console.log("Kommunicate create conversation successfull : " + response);
      },(response) => {
        console.log("Kommunicate create conversation failed : " + response);
      });
    },
    (response)=>{
    });
  }

**Comment by reytum** [comment]
@kinZz23 There maybe be any of the below reason for this issue (Every step needs to be followed):

1) The Plugin has not been add to the project(Please check the plugin list - ionic cordova plugin ls)
2) 'kommunicate' has not been defined (You need to define kommunicate at the end of the file - declare var kommunicate: any;)
3) The app is being run on a web browser(This plugin is a wrapper around native platforms, so it supports only android and iOS platforms)

**Comment by kinZz23** [comment]
@reytum Thanks for the reply.
**1.Plugin is already added** 

**My package.json:**
"dependencies": {
    "@angular/animations": "5.2.11",
    "@angular/common": "5.2.11",
    "@angular/compiler": "5.2.11",
    "@angular/compiler-cli": "5.2.11",
    "@angular/core": "5.2.11",
    "@angular/forms": "5.2.11",
    "@angular/http": "5.2.11",
    "@angular/platform-browser": "5.2.11",
    "@angular/platform-browser-dynamic": "5.2.11",
    "@ionic-native/camera": "^4.8.0",
    "@ionic-native/core": "4.7.0",
    "@ionic-native/in-app-browser": "^4.9.0",
    "@ionic-native/onesignal": "^4.8.0",
    "@ionic-native/social-sharing": "^4.9.0",
    "@ionic-native/splash-screen": "4.7.0",
    "@ionic-native/status-bar": "4.7.0",
    "@ionic/storage": "2.1.3",
    "Kommunicate-Cordova-Ionic-PhoneGap-Chat-Plugin": "git+https://github.com/Kommunicate-io/Kommunicate-Cordova-Ionic-PhoneGap-Chat-Plugin.git",
    "cordova-android": "7.0.0",
    "cordova-plugin-cocoapod-support": "^1.5.0",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-inappbrowser": "^3.0.0",
    "cordova-plugin-ionic-keyboard": "^2.0.5",
    "cordova-plugin-ionic-webview": "^1.1.19",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-swift-support": "^3.1.1",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova-plugin-x-socialsharing": "^5.4.1",
    "es6-promise-plugin": "^4.2.2",
    "io.kommunicate.phonegap": "https://github.com/Kommunicate-io/Kommunicate-Cordova-Ionic-PhoneGap-Chat-Plugin.git",
    "ionic-angular": "3.9.2",
    "ionicons": "3.0.0",
    "onesignal-cordova-plugin": "^2.4.1",
    "rxjs": "5.5.11",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.26"
  },

**2. Variable is already declared:**

**last line of event-names.ts is:**
declare var kommunicate: any;

**3.Is there anything extra for running the chat via android mobile I found this in sample app for ios:**
I added this below lines manually in my config.xml: 
 <feature name="KommunicateCordovaPlugin">
        <param name="ios-package" value="KommunicateCordovaPlugin" />
        <param name="onload" value="true" />
    </feature>

**Comment by kinZz23** [comment]
ionic cordova plugin ls
> cordova plugin ls
cordova-plugin-cocoapod-support 1.5.0 "Cordova CocoaPods Dependency Support"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.1.19 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-swift-support 3.1.1 "SwiftSupport"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.4.1 "SocialSharing"
es6-promise-plugin 4.2.2 "Promise"
io.kommunicate.phonegap 0.1.0 "Kommunicate"
onesignal-cordova-plugin 2.4.1 "OneSignal Push Notifications"

**Comment by kinZz23** [comment]
okay got this issue solved by command **cordova clean android**

**Comment by jongbonga** [comment]
I'm still struggling to make this one work, can you share a working  sample

**Comment by reytum** [comment]
@jongbonga What is the command you are using to run the app?
You can checkout the samples here: https://github.com/Kommunicate-io/Kommunicate-Ionic-Cordova-Sample-App
