### ISSUE TITLE
Not able to add plugin on Cordova v9

### ISSUE THREAD

**Issue by iouhammi** [Kommunicate-io/Kommunicate-Cordova-Ionic-PhoneGap-Chat-Plugin#11]
Hello,

I am not able to add plugin to my ionic/cordova project. I get the following error:

```
Using "requireCordovaModule" to load non-cordova module "glob" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.
[ERROR] An error occurred while running cordova plugin add kommunicate-cordova-plugin --save (exit code 1).
```
I am using ionic 3 with 9.0.0 (cordova-lib@9.0.1).

When I rollback to Cordova 8 everything is working fine. This issue occurs only when I upgrade to Cordova 9.

**Comment by amatelic** [comment]
I am encountering the same problem, on ionic 9 the plugin is not working. Getting the same error as above.

**Comment by reytum** [comment]
@iouhammi @amatelic We'll be releasing a fix for by next week.

**Comment by amatelic** [comment]
Are there any updates to the fix?

**Comment by reytum** [comment]
@amatelic @iouhammi we have released a new version with Cordova 9 support. The version is 0.4.13 . Let us know if you face any issues with this version.
