### ISSUE TITLE
Kommunicate giving exception when logging in in Release Build but working good in Debug Build 

### ISSUE THREAD

**Issue by gcardinale** [Kommunicate-io/Kommunicate-Cordova-Ionic-PhoneGap-Chat-Plugin#23]
I have this problem in capacitor ionic. Check https://github.com/Kommunicate-io/Kommunicate-Android-Chat-SDK/issues/79 solution but not working.

**Comment by Samir1810** [comment]
We shall update on the chat you opened and will update you there.
