### ISSUE TITLE
Could not find io.kommunicate.sdk:kommunicateui:2.3.8.

### ISSUE THREAD

**Issue by sushantadita** [Kommunicate-io/Kommunicate-Cordova-Ionic-PhoneGap-Chat-Plugin#35]
**I am using ionic 6 getting error** 
Execution failed for task ':app:processDebugMainManifest'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find io.kommunicate.sdk:kommunicateui:2.3.8.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/io/kommunicate/sdk/kommunicateui/2.3.8/kommunicateui-2.3.8.pom
       - https://repo.maven.apache.org/maven2/io/kommunicate/sdk/kommunicateui/2.3.8/kommunicateui-2.3.8.pom
       
Please help me

**Comment by amntoppo** [comment]
If using Gradle 6.7 or lower, add the following code to your root build.gradle file:

```
allprojects {
    repositories {
        maven { url 'https://kommunicate.jfrog.io/artifactory/kommunicate-android-sdk' }
    }
}
```

Copy
If using Gradle 6.8 or higher, add the following to your settings.gradle file:

```
dependencyResolutionManagement {
    repositories {
        maven { url 'https://kommunicate.jfrog.io/artifactory/kommunicate-android-sdk' }
    }
}
```

**Comment by sushantadita** [comment]
facing same issue

**Comment by GauravDadhich13** [comment]
getting same error please give the solution asap

**Comment by amntoppo** [comment]
In your build.gradle file, check if you have these dependencies:
```
google()
mavenCentral()
```

If that does not resolve your issue, please share the build.gradle file
