### ISSUE TITLE
Problems on Ionic 3 

### ISSUE THREAD

**Issue by BadiuAlexandru** [Kommunicate-io/Kommunicate-Cordova-Ionic-PhoneGap-Chat-Plugin#7]
Hello, I use this plugin to integrate my ionic project with kommunicate. On Ios it works great, but I have a problem with the Android. After I install the plugin and run `ionic cordova build --release android` I get the following error `Execution failed for task ':app:transformDexWithDexForRelease'` .

Do you have some ideas how I can solve this?

**Comment by elieobeid7** [comment]
Does this issue still exists on ionic 4?

**Comment by reytum** [comment]
@BadiuAlexandru @elieobeid7 please enable multidex. Follow this link :https://stackoverflow.com/questions/34259679/enable-multidex-for-android-in-ionic-framework
Post that do a clean build.

**Comment by elieobeid7** [comment]
@BadiuAlexandru Thank you for your response.
